# Mapping normalisasi untuk singkatan atau istilah hukum
NORMALIZATION_MAP = {
    "undang undang": "uu",
    "undang-undang": "uu",
    "uu": "uu",
    "peraturan pemerintah": "pp",
    "pp": "pp",
    "peraturan presiden": "perpres",
    "perpres": "perpres",
    "peraturan pemerintah pengganti undang undang": "perppu",
    "perppu": "perppu",
    "peraturan menteri": "permen",
    "permen": "permen",
    "peraturan menteri keuangan": "permenkeu",
    "permenkeu": "permenkeu",
    "peraturan menteri dalam negeri": "permendagri",
    "permendagri": "permendagri",
    "peraturan menteri kesehatan": "permenkes",
    "permenkes": "permenkes",
    "peraturan menteri pendidikan dan kebudayaan": "permendikbud",
    "permendikbud": "permendikbud",
    "peraturan menteri ketenagakerjaan": "permenaker",
    "permenaker": "permenaker",
    "peraturan menteri perhubungan": "permenhub",
    "permenhub": "permenhub",
    "peraturan daerah": "perda",
    "perda": "perda",
    "peraturan gubernur": "pergub",
    "pergub": "pergub",
    "peraturan bupati": "perbup",
    "perbup": "perbup",
    "peraturan wali kota": "perwali",
    "perwali": "perwali",
    "mahkamah agung": "ma",
    "ma": "ma",
    "mahkamah konstitusi": "mk",
    "mk": "mk",
    "pengadilan negeri": "pn",
    "pn": "pn",
    "pengadilan agama": "pa",
    "pa": "pa",
    "pengadilan tinggi": "pt",
    "pt": "pt",
    "tata usaha negara": "tun",
    "tun": "tun",
    "pengadilan tata usaha negara": "ptun",
    "ptun": "ptun",
    "surat keputusan": "sk",
    "sk": "sk",
    "perdata": "pdt",
    "pdt": "pdt",
    "surat edaran": "se",
    "se": "se",
    "instruksi presiden": "inpres",
    "inpres": "inpres",
    "keputusan presiden": "kepres",
    "kepres": "kepres",
    "keputusan menteri": "kepmen",
    "kepmen": "kepmen",
    "kitab undang undang hukum pidana": "kuhp",
    "kuhp": "kuhp",
    "kitab undang undang hukum perdata": "kuhper",
    "kuhper": "kuhper",
    "anggaran pendapatan dan belanja negara": "apbn",
    "apbn": "apbn",
    "anggaran pendapatan dan belanja daerah": "apbd",
    "apbd": "apbd",
    "pajak pertambahan nilai": "ppn",
    "ppn": "ppn",
    "komisi pemberantasan korupsi": "kpk",
    "pemutusan hubungan kerja": "phk",
    "phk": "phk",
    "tindak pidana pencucian uang": "tppu",
    "perbuatan melawan hukum": "pmh",
    "pmh": "pmh",
    "perjanjian kerja sama": "pks",
    "cidera janji": "wanprestasi",
    "peninjauan kembali": "pk",
    "pk": "pk",
    "penundaan kewajiban pembayaran utang": "pkpu",
    "pkpu": "pkpu",
    "penanaman modal asing": "pma",
    "pma": "pma",
    "penanaman modal dalam negeri": "pmdn",
    "pmdn": "pmdn",
    "peraturan otoritas jasa keuangan": "pojk",
    "pojk": "pojk",
    "otoritas jasa keuangan": "ojk",
    "ojk": "ojk",
    "pengujian undang undang": "puu",
    "puu": "puu",
    "pejabat pembuat akta tanah": "ppat",
    "ppat": "ppat",
    "perjanjian pengikatan jual beli": "ppjb",
    "ppjb": "ppjb",
    "surat kuasa membebankan hak tanggungan": "skmht",
    "skmht": "skmht",
    "undang undang jabatan notaris": "uujn",
    "uujn": "uujn",
    "undang undang perlindungan konsumen": "uupk",
    "uupk": "uupk",
    "badan arbitrase nasional indonesia": "bani",
    "bani": "bani",
    "tanggung jawab sosial perusahaan": "csr",
    "csr": "csr",
    "rapat umum pemegang saham": "rups",
    "rups": "rups",
    "warga negara indonesia": "wni",
    "wni": "wni",
    "warga negara asing": "wna",
    "wna": "wna",
    "aparatur sipil negara": "asn",
    "asn": "asn",
    "pegawai negeri sipil": "pns",
    "pns": "pns",
    "tentara nasional indonesia": "tni",
    "tni": "tni",
    "usaha mikro kecil dan menengah": "umkm",
    "umkm": "umkm",
    "usaha mikro kecil": "umk",
    "umk": "umk",
    "badan usaha milik negara": "bumn",
    "bumn": "bumn",
    "badan usaha milik daerah": "bumd",
    "bumd": "bumd",
    "kantor pelayanan kekayaan negara dan lelang": "kpknl",
    "kpknl": "kpknl",
    "badan narkotika nasional": "bnn",
    "bnn": "bnn",
    "kartu tanda penduduk": "ktp",
    "ktp": "ktp",
}
